apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1 #statefulset as its DB
  selector:
    matchLabels:
      app: webapp
  template: # POD configuration
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webappimg
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret # name of mongo-secret yaml file
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret # name of mongo-secret yaml file
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config # name of mongo-secret yaml file
                  key: mongo-url
          resources:
            limits:
              cpu: "0.5" # specify the CPU limit (in cores)
              memory: "256Mi" # specify the memory limit (in megabytes)
            requests:
              cpu: "0.2" # specify the CPU request (in cores)
              memory: "128Mi" # specify the memory request (in megabytes)
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp # match labels of POD
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # match with containerPort
      nodePort: 30001
